Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 900
      MemorySize: 512
      Handler: helloworld.App
      CodeUri: /home/carlossmartins22/dev/study/Code101-lambda/HelloWorldFunction
      Runtime: java21
      Architectures:
        - x86_64